version: "3.6"

services:
  postgres:
    image: postgres
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-Passmefast}
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 5050:80

  note:
    image: note:development<localBuild>
    hostname: "note"
    depends_on:
      - postgres
    ports:
      - 9000:9000
      - 9102:9102
      - 9095:9095
      - 5266:5266
    environment:
      HTTP_ADDRESS: "0.0.0.0"
      HTTP_PORT: 9000
      SERVICE_NAME: "note"
      REQUIRED_CONTACT_POINT_NR: 1
      EVENTS_BATCH_THRESHOLD: 2
      NUM_SNAPSHOTS_TO_RETAIN: 2
      PROTO_PACKAGE: "com.sharonsyra.protobuf.note"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Passmefast
      POSTGRES_DB_NAME: postgres
